version: '2'
services:
  api:
    build: .
    image: canary-api
    container_name: canary-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
      - worker
      - queue

  worker:
    image: canary-api
    container_name: canary-worker
    depends_on:
      - queue
    links:
      - queue
    command: su -m canary-worker -c 'celery --app=app.worker.tasks worker'

  db:
    image: postgres:latest
    container_name: canary-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canaryDB
    ports:
      - "5432:5432"

  queue:
    image: redis:latest
    container_name: canary-queue
    ports:
      - "6379:6379"
